self.__precacheManifest = [
    {"url": "index.html"},
    {"url": "restaurant.html"},
    {"url": "css/styles.min.css"},
    {"url": "js/main.js"},
    {"url": "js/restaurant.js"},
    {"url": "js/scripts.min.js"},
    {"url": "img/1.jpg"},
    {"url": "img/2.jpg"},
    {"url": "img/3.jpg"},
    {"url": "img/4.jpg"},
    {"url": "img/5.jpg"},
    {"url": "img/6.jpg"},
    {"url": "img/7.jpg"},
    {"url": "img/8.jpg"},
    {"url": "img/9.jpg"},
    {"url": "img/10.jpg"},
    {"url": "img/undefined.jpg"},
];